### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function getName() on null

### ISSUE THREAD

**Issue by koskinenaa** [CheckoutFinland/checkout-finland-for-woocommerce#11]
Hi,

just to let you know, I recieved the following error on a webstore using the 1.1.6 version of this plugin.

```
PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in path/to/wp-content/plugins/woocommerce-checkout-finland-gateway/src/Gateway.php:712
Stack trace:
#0 path/to/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(924): CheckoutFinland\WooCommercePaymentGateway\Gateway->process_payment(some_id)
#1 path/to/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1124): WC_Checkout->process_order_payment(some_id, 'checkout_finlan...')
#2 path/to/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(462): WC_Checkout->process_checkout()
#3 path/to/wp-includes/class-wp-hook.php(286): WC_AJAX::checkout('')
#4 path/to/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 path/to/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#6 path/to/wp- in path/to/wp-content/plugins/woocommerce-checkout-finland-gateway/src/Gateway.php on line 712
```
I've now updated the plugin to 1.1.7 and after RTFM'ing did the _composer install_ inside the plugin dir after manual install. I'll report back, if the above error persists.

**Comment by loueranta** [comment]
Thanks for letting us know. Please do keep us updated if the problem persists.

The plugin will be released on Wordpress.org in the next couple of weeks, so updating the plugin will be easier in the future.
